#!/usr/bin/env bash
set -e
pair=dgxusd
sources=(
  bitfinex
)

case $1 in
  bitfinex) {
    dgx_usdt=$(setzer x-price "$1" dgxusd)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$dgx_usdt * $usdt_usd")"
  };;
  *) {
    export SETZER_MIN_MEDIAN=2
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
