#!/usr/bin/env bash
set -e
pair=mana:usd
sources=(
  binance
  binance_us
  coinbase
  ftx
  okx
  kraken
  upbit
)

case $1 in
  binance_us|coinbase|ftx|kraken) {
    setzer x-price "$1" $pair
  };;
  binance|okx) {
    mana_usdt=$(setzer x-price "$1" mana:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$mana_usdt *$usdt_usd")"
  };;
  upbit) {
    mana_krw=$(setzer x-price "$1" mana:krw)
    krw_usd=$(setzer x-price fx krwusd)
    setzer --format "$(bc -l <<<"$mana_krw * $krw_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
