#!/usr/bin/env bash
set -e
pair=linkusd
sources=(
  binance
  bitstamp
  coinbase
  ftx
  gemini
  kraken
  uniswap_v3
)

case $1 in
  binance) {
    link_usdt=$(setzer x-price "$1" link:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$link_usdt * $usdt_usd")"
  };;
  bitstamp|coinbase|ftx|gemini|kraken) {
    setzer x-price "$1" link:usd
  };;
  uniswap_v3) {
    link_eth=$(setzer x-price "$1" link:eth)
    eth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$link_eth * $eth_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac