#!/usr/bin/env bash
set -e
[ "$DEBUG" == 'true' ] && set -x

src=$1
pair=${2/:/}

if [[ ${#2} -eq 6 ]]; then
  base=${pair:0:3}
  quote=${pair:3:6}
else
  base=${2%:*}
  quote=${2#*:}
fi

# Setting up base URLs for exchanges
ORIGIN_THEGRAPH_URL="${ORIGIN_THEGRAPH_URL:-https://api.thegraph.com}"
ORIGIN_BINANCE_URL="${ORIGIN_BINANCE_URL:-https://www.binance.com}"
ORIGIN_BINANCE_US_URL="${ORIGIN_BINANCE_US_URL:-https://www.binance.us}"
ORIGIN_BITFINEX_URL="${ORIGIN_BITFINEX_URL:-https://api.bitfinex.com}"
ORIGIN_BITSTAMP_URL="${ORIGIN_BITSTAMP_URL:-https://www.bitstamp.net}"
ORIGIN_BITTHUMB_URL="${ORIGIN_BITTHUMB_URL:-https://global-openapi.bithumb.pro}"
ORIGIN_BITTREX_URL="${ORIGIN_BITTREX_URL:-https://api.bittrex.com}"
ORIGIN_CMC_URL="${ORIGIN_CMC_URL:-https://pro-api.coinmarketcap.com}"
ORIGIN_COINBASE_URL="${ORIGIN_COINBASE_URL:-https://api.pro.coinbase.com}"
ORIGIN_CRYPTOCOMPARE_URL="${ORIGIN_CRYPTOCOMPARE_URL:-https://min-api.cryptocompare.com}"
ORIGIN_DDEX_URL="${ORIGIN_DDEX_URL:-https://api.ddex.io}"
ORIGIN_FX_URL="${ORIGIN_FX_URL:-https://openexchangerates.org/api/}"
ORIGIN_GATEIO_URL="${ORIGIN_GATEIO_URL:-https://fx-api.gateio.ws}"
ORIGIN_GEMINI_URL="${ORIGIN_GEMINI_URL:-https://api.gemini.com}"
ORIGIN_HITBTC_URL="${ORIGIN_HITBTC_URL:-https://api.hitbtc.com}"
ORIGIN_HUOBI_URL="${ORIGIN_HUOBI_URL:-https://api.huobi.pro}"
ORIGIN_KRAKEN_URL="${ORIGIN_KRAKEN_URL:-https://api.kraken.com}"
ORIGIN_KUCOIN_URL="${ORIGIN_KUCOIN_URL:-https://api.kucoin.com}"
ORIGIN_OKEX_URL="${ORIGIN_OKEX_URL:-https://www.okex.com}"
ORIGIN_OKX_URL="${ORIGIN_OKX_URL:-https://www.okx.com}"
ORIGIN_POLONIEX_URL="${ORIGIN_POLONIEX_URL:-https://poloniex.com}"
ORIGIN_UPBIT_URL="${ORIGIN_UPBIT_URL:-https://api.upbit.com}"
ORIGIN_GSU_URL="${ORIGIN_GSU_URL:-https://goerli.gsu.io/Umbraco/Api/Rates/GSU/?symbol}"

# Wrap curl and surface error on mismatch of expected HTTP status
curl_stat() {
    expected="$1"; shift;
    payload=$(curl -w "\n%{http_code}\n" "$@")
    stat=$(echo "$payload" | tail -n 1)
    body=$(echo "$payload" | sed \$d)
    echo "$body"
    [[ "$stat" = "$expected" ]]
}

case $src in
 gsu) {
    json=$(curl_stat 200 -sS "$ORIGIN_GSU_URL=$pair")
    setzer --format "$(echo "scale=5;$(jshon <<< "$json" -e price -u)/10^18" | bc)"
  };;
  balancer) {
    case "${pair^^}" in
      BALUSD) {
        id="0xba100000625a3754423978a60c9317c58a424e3d"
      };;
      AAVEUSD) {
        id="0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"
      };;
      WNXMUSD) {
        id="0x0d438f3b5175bebc262bf23753c1e53d03432bde"
      };;
    esac
    json=$(curl_stat 200 \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { tokenPrices(where: { id: $id }) { symbol price poolLiquidity } }", "variables": { "id": "'"$id"'" } }' \
      "$ORIGIN_THEGRAPH_URL/subgraphs/name/balancer-labs/balancer")
    setzer --format "$(jshon <<<"$json" -e data -e tokenPrices -e 0 -e price -u)"
  };;
  balancer_v2) {
    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
    case "${pair^^}" in
      WSTETHETH) {
        pool_addr=32296969ef14eb0c6d29669c550d4a0449130230 # wstETH/wETH pool, but prices expressed in stETH/ETH
      };;
      WETHYFI) {
        pool_addr=186084ff790c65088ba694df11758fae4943ee9e # YFI/wETH pool
      };;
      RETHETH) {
        pool_addr=1e19cf2d73a72ef1332c882f20534b6519be0276 # rETH/wETH, but price returned by the pool includes the staking gains
      };;
      GNOWETH) {
        pool_addr=0xF4C0DD9B82DA36C07605df83c8a416F11724d88b
      };;
    esac
    # keccak256("getLatest(uint8)")
    getLatest_method_id=b10be739

    tokenprice=$(setzer \
      --eth-call \
      "$pool_addr" \
      "$getLatest_method_id" \
      "0000000000000000000000000000000000000000000000000000000000000000")  #PAIR_PRICE

    # for Balancer Metastable pools, we must use the rate used by the internal Rate Provider
    # and convert the response from getLatest
    case "${pair^^}" in
      WSTETHETH) {
        # wstETH is a non-rebasing wrapper that exposes the underlying stETH shares
        # converting stETH price to wstETH
        token_contract_addr=0000000000000000000000007f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
      };;
      RETHETH) {
        # rETH is not rebasing, but its value increases over time respective to ETH
        # converting ETH price to rETH
        token_contract_addr=000000000000000000000000ae78736cd615f374d3085123a210448e74fc6393
      };;
    esac

    #Extra processing for MetaStable pools
    if [[ -n $token_contract_addr ]]; then
      # keccak256("getPriceRateCache(address)")
      getPriceRateCache_method_id=b867ee5a
      res=$(setzer --eth-call "$pool_addr" "$getPriceRateCache_method_id" "$token_contract_addr")
      Rate=${res:0:64}
      # price = RateProviderRate * CurveTokenprice
      price=$(bc -l <<<"ibase=16; (${Rate^^} * ${tokenprice^^} / ${ten_to_18^^} / ${ten_to_18^^})")
    else
      price=$(bc -l <<<"ibase=16; (${tokenprice^^} / ${ten_to_18^^})")
    fi

    if [[ -n $price ]]; then
      setzer --format $price
    fi
  };;
  binance) {
    json=$(curl_stat 200 -sS "${ORIGIN_BINANCE_URL}/api/v3/ticker/price?symbol=${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e price -u)"
  };;
  binance_us) {
    json=$(curl_stat 200 -sS "${ORIGIN_BINANCE_US_URL}/api/v3/ticker/price?symbol=${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e price -u)"
  };;
  bitfinex) {
    json=$(curl_stat 200 -sS "${ORIGIN_BITFINEX_URL}/v2/ticker/t${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e 6)"
  };;
  bitstamp) {
    json=$(curl_stat 200 -sS "${ORIGIN_BITSTAMP_URL}/api/v2/ticker/${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  bitthumb) {
    json=$(curl_stat 200 -sS "${ORIGIN_BITTHUMB_URL}/openapi/v1/spot/ticker?symbol=${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e 0 -e c -u)"
  };;
  bittrex) {
    json=$(curl_stat 200 -sS "${ORIGIN_BITTREX_URL}/api/v1.1/public/getticker?market=${quote^^}-${base^^}")
    setzer --format "$(jshon <<<"$json" -e result -e Last -u)"
  };;
  cmc) {
    ticker=$(case "${pair^^}" in
      USDTUSD) { echo "825";  };;
      POLYUSD) { echo "2496"; };;
    esac)
    json=$(curl_stat 200 -sS -H "X-CMC_PRO_API_KEY:  $CMC_API_KEY" -H "Accept: application/json" -d  "id=$ticker" -G ${ORIGIN_CMC_URL}/v1/cryptocurrency/quotes/latest)
    setzer --format "$(jshon <<<"$json" -e data -e "$ticker" -e quote -e USD -e price -u)"
  };;
  coinbase) {
    json=$(curl_stat 200 -sS "${ORIGIN_COINBASE_URL}/products/${base^^}-${quote^^}/ticker")
    setzer --format "$(jshon <<<"$json" -e price -u)"
  };;
  cryptocompare) {
    json=$(curl_stat 200 -sS "${ORIGIN_CRYPTOCOMPARE_URL}/data/price?fsym=${base^^}&tsyms=${quote^^}")
    setzer --format "$(jshon <<<"$json" -e USD -u)"
  };;
  curve) {
    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
    case "${pair^^}" in
      WSTETHETH) {
        crv_contract_addr=DC24316b9AE028F1497c275EB9192a3Ea0f67022 # stETH/ETH pool
        crv_src_token=$(printf '%064X' 1) # stETH index
        crv_dst_token=$(printf '%064X' 0) # ETH index
        crv_src_amount=$ten_to_18
      };;
      RETHWSTETH) {
        crv_contract_addr=447ddd4960d9fdbf6af9a790560d0af76795cb08 # stETH/ETH pool
        crv_src_token=$(printf '%064X' 0) # rETH index
        crv_dst_token=$(printf '%064X' 1) # wstETH index
        crv_src_amount=$ten_to_18
      };;
      *) {
        echo >&2 "Error: pair not supported for Curve exchange: $pair"
      };;
    esac
    # keccak256("get_dy(int128,int128,uint256)")
    get_dy_method_id=5e0d443f
    crv_dst_amount=$(setzer \
      --eth-call \
      "$crv_contract_addr" \
      "$get_dy_method_id" \
      "$crv_src_token$crv_dst_token$crv_src_amount"
    )
    case "${pair^^}" in
      WSTETHETH) {
        # wstETH is a non-rebasing wrapper that exposes the underlying stETH shares
        wsteth_contract_addr=7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
        # keccak256("stEthPerToken()")
        steth_per_token_method_id=035faf82
        # how many stETH wei one would receive by unwarpping 10^18 wstETH wei
        steth_per_wsteth=$(setzer --eth-call "$wsteth_contract_addr" "$steth_per_token_method_id")
        # wstethEthPrice = stethPerWsteth * stethEthPrice
        price=$(bc -l <<<"ibase=16; (${steth_per_wsteth^^} * ${crv_dst_amount^^}) / (${crv_src_amount^^} * ${ten_to_18^^})")
      };;
      *) {
        price=$(bc -l <<<"ibase=16; ${crv_dst_amount^^} / ${crv_src_amount^^}")
      };;
    esac
    if [[ -n $price ]]; then
      setzer --format $price
    fi
  };;
  ddex) {
    json=$(curl_stat 200 -sS "${ORIGIN_DDEX_URL}/v4/markets/${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e market -e lastPrice -u)"
  };;
  fx) {
    json=$(curl_stat 200 -sS -L "${ORIGIN_FX_URL}/latest.json?app_id=${EXCHANGERATES_API_KEY}&base=${base^^}")
    setzer --format "$(jshon <<<"$json" -e rates -e "${quote^^}" -u)"
  };;
  gateio) {
    json=$(curl_stat 200 -sS "${ORIGIN_GATEIO_URL}/api/v4/spot/tickers?currency_pair=${base^^}_${quote^^}")
    setzer --format "$(jshon <<<"$json" -e 0 -e last -u)"
  };;
  gemini) {
    json=$(curl_stat 200 -sS "${ORIGIN_GEMINI_URL}/v1/pubticker/${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  hitbtc) {
    json=$(curl_stat 200 -sS "${ORIGIN_HITBTC_URL}/api/2/public/ticker/${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  huobi) {
    json=$(curl_stat 200 -sS "${ORIGIN_HUOBI_URL}/market/detail/merged?symbol=${base,,}${quote,,}")
    setzer --format "$(jshon <<<"$json" -e tick -e bid -e 0)"
  };;
  kraken) {
    json=$(curl_stat 200 -sS "${ORIGIN_KRAKEN_URL}/0/public/Ticker?pair=${base^^}${quote^^}")
    setzer --format "$(jshon <<<"$json" -e result -e "${base^^}${quote^^}" -e c -e 0 -u)"
  };;
  kucoin) {
    json=$(curl_stat 200 -sS "${ORIGIN_KUCOIN_URL}/api/v1/market/orderbook/level1?symbol=${base^^}-${quote^^}")
    setzer --format "$(jshon <<<"$json" -e data -e price -u)"
  };;
  okex) {
    json=$(curl_stat 200 -sS "${ORIGIN_OKEX_URL}/api/spot/v3/instruments/${base^^}-${quote^^}/ticker")
    setzer --format "$(jshon <<<"$json" -e last -u)"
  };;
  okx) {
    json=$(curl_stat 200 -sS "${ORIGIN_OKX_URL}/api/v5/market/ticker?instId=${base^^}-${quote^^}-SWAP")
    setzer --format "$(jshon <<<"$json" -e data -e 0 -e last -u)"
  };;
  poloniex) {
    json=$(curl_stat 200 -sS "${ORIGIN_POLONIEX_URL}/public?command=returnTicker")
    setzer --format "$(jshon <<<"$json" -e "${quote^^}"_"${base^^}" -e last -u)"
  };;
  rocketpool) {
    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
    # RETHETH only
    contract_addr="0xae78736Cd615f374D3085123A210448E74Fc6393"

    # keccak256("getExchangeRate()")
    get_rate_method_id=e6aa216c
    rate=$(setzer \
      --eth-call \
      "$contract_addr" \
      "$get_rate_method_id"
    )
    price=$(bc -l <<<"ibase=16; ${rate^^} / ${ten_to_18^^}")
    if [[ -n $price ]]; then
      setzer --format $price
    fi
  };;
  sushiswap) {
    case "${pair^^}" in
      SNXETH) {
        id="0xa1d7b2d891e3a1f9ef4bbc5be20630c2feb1c470"
        select="token1Price"
      };;
      CRVETH) {
        id="0x58dc5a51fe44589beb22e8ce67720b5bc5378009"
        select="token0Price"
      };;
      WETHYFI) {
        id="0x088ee5007c98a9677165d78dd2109ae4a3d04d0c"
        select="token0Price"
      };;
    esac
    json=$(curl_stat 200 \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pairs(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/zippoxer/sushiswap-subgraph-fork)
    setzer --format "$(jshon <<<"$json" -e data -e pairs -e 0 -e $select -u)"
  };;
  uniswap) {
    case "${pair^^}" in
      AAVEETH) {
        id="0xdfc14d2af169b0d36c4eff567ada9b2e0cae044f"
        select="token1Price"
      };;
      BALETH) {
        id="0xa70d458a4d9bc0e6571565faee18a48da5c0d593"
        select="token1Price"
      };;
      LRCETH) {
        id="0x8878df9e1a7c87dcbf6d3999d997f262c05d8c70"
        select="token1Price"
      };;
      PAXGETH) {
        id="0x9c4fe5ffd9a9fc5678cfbd93aa2d4fd684b67c4c"
        select="token1Price"
      };;
      SNXETH) {
        id="0x43ae24960e5534731fc831386c07755a2dc33d47"
        select="token1Price"
      };;
    esac
    json=$(curl_stat 200 \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pairs(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/uniswap/uniswap-v2)
    setzer --format "$(jshon <<<"$json" -e data -e pairs -e 0 -e $select -u)"
  };;
  uniswap_v3) {
    case "${pair^^}" in
      COMPETH) {
        id="0xea4ba4ce14fdd287f380b55419b1c5b6c3f22ab6"
        select="token1Price"
      };;
      ETHUSDC) {
        id="0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"
        select="token0Price"
      };;
      UNIETH) {
        id="0x1d42064fc4beb5f8aaf85f4617ae8b3b5b8bd801"
        select="token1Price"
      };;
      YFIETH) {
        id="0x04916039b1f59d9745bf6e0a21f191d1e0a84287"
        select="token1Price"
      };;
      CRVETH) {
        id="0x4c83a7f819a5c37d64b4c5a2f8238ea082fa1f4e"
        select="token0Price"
      };;
      LINKETH) {
        id="0xa6cc3c2531fdaa6ae1a3ca84c2855806728693e8"
        select="token1Price"
      };;
      GNOETH) {
        id="0xf56d08221b5942c428acc5de8f78489a97fc5599"
        select="token1Price"
      };;
      WNXMETH) {
        id="0x058d79a4c6eb5b11d0248993ffa1faa168ddd3c0"
        select="token1Price"
      }
    esac
    json=$(curl_stat 200 \
      -sS \
      -X POST \
      -H "Content-Type: application/json" \
      --data '{ "query": "query($id:String) { pools(where: { id: $id }) { token0Price token1Price } }", "variables": { "id": "'"$id"'" } }' \
      ${ORIGIN_THEGRAPH_URL}/subgraphs/name/uniswap/uniswap-v3)
    setzer --format "$(jshon <<<"$json" -e data -e pools -e 0 -e $select -u)"
  };;
  upbit) {
    json=$(curl_stat 200 -sS "${ORIGIN_UPBIT_URL}/v1/ticker?markets=${quote^^}-${base^^}")
    setzer --format "$(jshon <<<"$json" -e 0 -e trade_price)"
  };;
  *) {
    echo >&2 "Error: exchange not recognised: $src"
  };;
esac
