#!/usr/bin/env bash
set -e
pair=maticusd
sources=(
  binance
  huobi
  coinbase
  gemini
  kraken
)

case $1 in
  coinbase|gemini|kraken) {
    setzer x-price "$1" matic:usd
  };;
  binance|huobi) {
    matic_usdt=$(setzer x-price "$1" matic:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l<<<"$matic_usdt * $usdt_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
