#!/usr/bin/env bash
set -e
pair=wbtcgsu
sources=(
gsu
gsu1
gsu2
)

case $1 in
   gsu) {
    setzer x-price "$1" "WBTC"
      };;
  gsu1) {
    setzer x-price "$1" "WBTC"
      };;
  gsu2) {
    setzer x-price "$1" "WBTC"
      };;

  *) {
    export SETZER_MIN_MEDIAN=1
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
