#!/usr/bin/env bash
set -e
pair=yfiusd
sources=(
  balancer_v2
  binance
  coinbase
  kraken
  okx
  sushiswap
)

case $1 in
  balancer_v2|sushiswap) {
    weth_yfi=$(setzer x-price "$1" weth:yfi)
    weth_usd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$weth_usd / $weth_yfi")"
  };;
  binance|okx) {
    yfi_usdt=$(setzer x-price "$1" yfi:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$yfi_usdt * $usdt_usd")"
  };;
  coinbase|kraken) {
    setzer x-price "$1" yfi:usd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
