#!/usr/bin/env bash
set -e
pair=btcgsu
sources=(
gsu
)

case $1 in
   gsu) {
    setzer x-price "$1" "BTC"
      };;

  *) {
    export SETZER_MIN_MEDIAN=1
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
