#!/usr/bin/env bash
set -e
pair=mkrusd
sources=(
  coinbase
  kraken
  gemini
  binance_us
  bitstamp
  uniswap_v3
)

case $1 in
  coinbase|kraken|gemini|binance_us|bitstamp) {
    setzer x-price "$1" mkr:usd
  };;
  uniswap_v3) {
    mkrweth=$(setzer x-price "$1" mkr:weth)
    wethusd=$(setzer price ethusd)
    setzer --format "$(bc -l <<<"$wethusd * $mkrweth")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
