#!/usr/bin/env bash
set -e
pair=yfiusd
sources=(
  balancer_v2
  binance
  coinbase
  ftx
  kraken
  okx
  sushiswap
)

case $1 in
  balancer_v2|sushiswap) {
    yfi_weth=$(setzer x-price "$1" yfi:weth)
    weth_usd=$(setzer price weth:usd)
    setzer --format "$(bc -l <<<"$yfi_weth * $weth_usd")"
  };;
  binance|okx) {
    yfi_usdt=$(setzer x-price "$1" yfi:usdt)
    usdt_usd=$(setzer price usdtusd)
    setzer --format "$(bc -l <<<"$yfi_usdt * $usdt_usd")"
  };;
  coinbase|ftx|kraken) {
    setzer x-price "$1" yfi:usd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac