#!/usr/bin/env bash
set -e
pair=kncusd
sources=(
  binance
  coinbase
  huobi
  upbit
)

case $1 in
  binance|huobi) {
    knc_btc=$(setzer x-price "$1" knc:btc)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$knc_btc * $btc_usd")"
  };;
  coinbase) {
    setzer --format "$(setzer x-price "$1" knc:usd)"
  };;
  upbit) {
    knc_krw=$(setzer x-price "$1" knc:krw)
    krw_usd=$(setzer x-price fx krw:usd)
    setzer --format "$(bc -l <<<"$knc_krw * $krw_usd")"
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
