#!/usr/bin/env bash
set -e
pair=usdtusd
sources=(
  binance
  bitfinex
  coinbase
  kraken
  okx
)

case $1 in
  binance|okx) {
    btc_usdt=$(setzer x-price "$1" btc:usdt)
    btc_usd=$(setzer price btcusd)
    setzer --format "$(bc -l <<<"$btc_usd / $btc_usdt")"
  };;
  bitfinex) {
    setzer x-price "$1" ust:usd
  };;
  coinbase) {
    setzer x-price "$1" usdt:usd
  };;
  kraken) {
    setzer x-price kraken usdt:zusd
  };;
  *) {
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
